# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - freebsd
julia:
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts

# after_success:
#   # push coverage results to Coveralls and Codecov
#   - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
